In [1]:
#elements acessings row/column
#loc and iloc---->location and index location based

In [7]:
 import pandas as pd
d=pd.DataFrame({"name":['pinky','pop','push','puppy'],#elements acessings row/column
#loc and iloc---->location and index location based"roll numbers":[123,456,678,234],"branch":['ece','cse','eee','mech']},index=[1,2,3,4])

In [8]:
d

name  roll numbers branch
1  pinky           123    ece
2    pop           456    cse
3   push           678    eee
4  puppy           234   mech

In [9]:
d.loc[1]

name            pinky
roll numbers      123
branch            ece
Name: 1, dtype: object

In [10]:
d.loc[2]['roll numbers']

456

In [11]:
d.iloc[0]

name            pinky
roll numbers      123
branch            ece
Name: 1, dtype: object

In [12]:
d.iloc[2]['roll numbers']

678

In [13]:
d.iloc[2]["branch"]

'eee'

In [14]:
d.describe()

roll numbers
count      4.000000
mean     372.750000
std      246.126492
min      123.000000
25%      206.250000
50%      345.000000
75%      511.500000
max      678.000000

In [15]:
d.count()

name            4
roll numbers    4
branch          4
dtype: int64

In [16]:
d.dtypes

name            object
roll numbers     int64
branch          object
dtype: object

In [17]:
d.count(axis='rows')

name            4
roll numbers    4
branch          4
dtype: int64

In [18]:
d.count(axis=1)

1    3
2    3
3    3
4    3
dtype: int64

In [19]:
d.count(axis=0)

name            4
roll numbers    4
branch          4
dtype: int64

In [20]:
d.set_index(["roll numbers","branch"])

name
roll numbers branch       
123          ece     pinky
456          cse       pop
678          eee      push
234          mech    puppy

In [21]:
d.set_index(["name"])

roll numbers branch
name                      
pinky           123    ece
pop             456    cse
push            678    eee
puppy           234   mech

In [22]:
import pandas
frame=pd.Series([9,3,5,6,21],[4,5,6,7,8])
frame

4     9
5     3
6     5
7     6
8    21
dtype: int64

In [23]:
frame.count()

5

In [24]:
import numpy as np
np.arange(3,9)

array([3, 4, 5, 6, 7, 8])

In [25]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
data=pd.DataFrame(np.arange(12).reshape(4,3))

In [28]:
data

0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [29]:
data=pd.DataFrame(np.arange(20).reshape(4,5),columns=list('abcde'))

In [30]:
data

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [31]:
data.loc[1,'b']=np.nan

In [32]:
data

a     b   c   d   e
0   0   1.0   2   3   4
1   5   NaN   7   8   9
2  10  11.0  12  13  14
3  15  16.0  17  18  19

In [33]:
data.isnull().sum()

a    0
b    1
c    0
d    0
e    0
dtype: int64

In [34]:
d+data

a   b branch   c   d   e name  roll numbers
0 NaN NaN    NaN NaN NaN NaN  NaN           NaN
1 NaN NaN    NaN NaN NaN NaN  NaN           NaN
2 NaN NaN    NaN NaN NaN NaN  NaN           NaN
3 NaN NaN    NaN NaN NaN NaN  NaN           NaN
4 NaN NaN    NaN NaN NaN NaN  NaN           NaN

In [35]:
dd.add(data,fill_value=1)


NameError: name 'dd' is not defined

In [36]:
np.random.rand(2,4)

array([[0.98254848, 0.76078496, 0.23706806, 0.65622651],
       [0.42558987, 0.90767149, 0.16849627, 0.38088143]])

In [37]:
np.random.randn(2,5)

array([[ 0.50105288, -0.90607777, -0.44630179,  0.62013324, -2.68111548],
       [-0.10059302, -0.40714592,  0.76353746,  1.5273055 , -2.11985877]])

In [38]:
#creating to dataframe with random values
r=pd.DataFrame(np.random.randn(3,10))
r

0         1         2         3         4         5         6  \
0  0.087469  0.296845 -1.006550  0.179500 -0.677944  1.881476  0.810192   
1 -0.470109 -0.858757  1.081208 -0.546980  0.238313  0.213670  0.166443   
2  0.106428 -0.613459 -1.350452  1.239993 -0.872730 -1.365315 -1.747859   

          7         8         9  
0 -0.826157 -0.697199  0.141897  
1 -1.235757  0.894851 -2.143308  
2  0.772715  0.876834  0.519280

In [39]:
r.index=['c','d','a']
r

0         1         2         3         4         5         6  \
c  0.087469  0.296845 -1.006550  0.179500 -0.677944  1.881476  0.810192   
d -0.470109 -0.858757  1.081208 -0.546980  0.238313  0.213670  0.166443   
a  0.106428 -0.613459 -1.350452  1.239993 -0.872730 -1.365315 -1.747859   

          7         8         9  
c -0.826157 -0.697199  0.141897  
d -1.235757  0.894851 -2.143308  
a  0.772715  0.876834  0.519280

In [40]:
r.column=['s1','s2','s3']
r

C:\Users\public\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  """Entry point for launching an IPython kernel.


0         1         2         3         4         5         6  \
c  0.087469  0.296845 -1.006550  0.179500 -0.677944  1.881476  0.810192   
d -0.470109 -0.858757  1.081208 -0.546980  0.238313  0.213670  0.166443   
a  0.106428 -0.613459 -1.350452  1.239993 -0.872730 -1.365315 -1.747859   

          7         8         9  
c -0.826157 -0.697199  0.141897  
d -1.235757  0.894851 -2.143308  
a  0.772715  0.876834  0.519280

In [41]:
#reindexing
r1=r.reindex(['a','c','b','d'])
r1

0         1         2         3         4         5         6  \
a  0.106428 -0.613459 -1.350452  1.239993 -0.872730 -1.365315 -1.747859   
c  0.087469  0.296845 -1.006550  0.179500 -0.677944  1.881476  0.810192   
b       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
d -0.470109 -0.858757  1.081208 -0.546980  0.238313  0.213670  0.166443   

          7         8         9  
a  0.772715  0.876834  0.519280  
c -0.826157 -0.697199  0.141897  
b       NaN       NaN       NaN  
d -1.235757  0.894851 -2.143308

In [42]:
r1.isnull().sum()

0    1
1    1
2    1
3    1
4    1
5    1
6    1
7    1
8    1
9    1
dtype: int64

In [43]:
r1.dropna()  # droping the null values

0         1         2         3         4         5         6  \
a  0.106428 -0.613459 -1.350452  1.239993 -0.872730 -1.365315 -1.747859   
c  0.087469  0.296845 -1.006550  0.179500 -0.677944  1.881476  0.810192   
d -0.470109 -0.858757  1.081208 -0.546980  0.238313  0.213670  0.166443   

          7         8         9  
a  0.772715  0.876834  0.519280  
c -0.826157 -0.697199  0.141897  
d -1.235757  0.894851 -2.143308

In [44]:
r1.fillna(3) # filling a null values

0         1         2         3         4         5         6  \
a  0.106428 -0.613459 -1.350452  1.239993 -0.872730 -1.365315 -1.747859   
c  0.087469  0.296845 -1.006550  0.179500 -0.677944  1.881476  0.810192   
b  3.000000  3.000000  3.000000  3.000000  3.000000  3.000000  3.000000   
d -0.470109 -0.858757  1.081208 -0.546980  0.238313  0.213670  0.166443   

          7         8         9  
a  0.772715  0.876834  0.519280  
c -0.826157 -0.697199  0.141897  
b  3.000000  3.000000  3.000000  
d -1.235757  0.894851 -2.143308

In [45]:
r1.fillna(method='bfill',axis=0).fillna(1) #backward filling

0         1         2         3         4         5         6  \
a  0.106428 -0.613459 -1.350452  1.239993 -0.872730 -1.365315 -1.747859   
c  0.087469  0.296845 -1.006550  0.179500 -0.677944  1.881476  0.810192   
b -0.470109 -0.858757  1.081208 -0.546980  0.238313  0.213670  0.166443   
d -0.470109 -0.858757  1.081208 -0.546980  0.238313  0.213670  0.166443   

          7         8         9  
a  0.772715  0.876834  0.519280  
c -0.826157 -0.697199  0.141897  
b -1.235757  0.894851 -2.143308  
d -1.235757  0.894851 -2.143308

In [46]:
r1.fillna(method='ffill',axis=1).fillna(1) # forward filling

0         1         2         3         4         5         6  \
a  0.106428 -0.613459 -1.350452  1.239993 -0.872730 -1.365315 -1.747859   
c  0.087469  0.296845 -1.006550  0.179500 -0.677944  1.881476  0.810192   
b  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
d -0.470109 -0.858757  1.081208 -0.546980  0.238313  0.213670  0.166443   

          7         8         9  
a  0.772715  0.876834  0.519280  
c -0.826157 -0.697199  0.141897  
b  1.000000  1.000000  1.000000  
d -1.235757  0.894851 -2.143308

In [47]:
r1.isnull()

0      1      2      3      4      5      6      7      8      9
a  False  False  False  False  False  False  False  False  False  False
c  False  False  False  False  False  False  False  False  False  False
b   True   True   True   True   True   True   True   True   True   True
d  False  False  False  False  False  False  False  False  False  False

In [48]:
r1.isna()

0      1      2      3      4      5      6      7      8      9
a  False  False  False  False  False  False  False  False  False  False
c  False  False  False  False  False  False  False  False  False  False
b   True   True   True   True   True   True   True   True   True   True
d  False  False  False  False  False  False  False  False  False  False

In [49]:
pd.isna(r1['s2'])

KeyError: 's2'

In [50]:
r1

0         1         2         3         4         5         6  \
a  0.106428 -0.613459 -1.350452  1.239993 -0.872730 -1.365315 -1.747859   
c  0.087469  0.296845 -1.006550  0.179500 -0.677944  1.881476  0.810192   
b       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
d -0.470109 -0.858757  1.081208 -0.546980  0.238313  0.213670  0.166443   

          7         8         9  
a  0.772715  0.876834  0.519280  
c -0.826157 -0.697199  0.141897  
b       NaN       NaN       NaN  
d -1.235757  0.894851 -2.143308

In [79]:
df33=pd.DataFrame({11:[5,6,7],12:[2,3,22],13:[4,5,8]})

In [80]:
df33

11  12  13
0   5   2   4
1   6   3   5
2   7  22   8

In [82]:
df33.replace(4,777)

11  12   13
0   5   2  777
1   6   3    5
2   7  22    8

In [81]:
df33.replace({2:44,3:45555})

11     12  13
0   5     44   4
1   6  45555   5
2   7     22   8

In [52]:
# index sorting and ranking
r2=r1.reindex(['a','c','b','e'])
r2

0         1         2         3         4         5         6  \
a  0.106428 -0.613459 -1.350452  1.239993 -0.872730 -1.365315 -1.747859   
c  0.087469  0.296845 -1.006550  0.179500 -0.677944  1.881476  0.810192   
b       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
e       NaN       NaN       NaN       NaN       NaN       NaN       NaN   

          7         8         9  
a  0.772715  0.876834  0.519280  
c -0.826157 -0.697199  0.141897  
b       NaN       NaN       NaN  
e       NaN       NaN       NaN

In [53]:
r2.sort_index()

0         1         2         3         4         5         6  \
a  0.106428 -0.613459 -1.350452  1.239993 -0.872730 -1.365315 -1.747859   
b       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
c  0.087469  0.296845 -1.006550  0.179500 -0.677944  1.881476  0.810192   
e       NaN       NaN       NaN       NaN       NaN       NaN       NaN   

          7         8         9  
a  0.772715  0.876834  0.519280  
b       NaN       NaN       NaN  
c -0.826157 -0.697199  0.141897  
e       NaN       NaN       NaN

In [54]:
r1.columns=['s0','s1','s2','s3','s4','s5','s6','s7','s8','s9']
r1

s0        s1        s2        s3        s4        s5        s6  \
a  0.106428 -0.613459 -1.350452  1.239993 -0.872730 -1.365315 -1.747859   
c  0.087469  0.296845 -1.006550  0.179500 -0.677944  1.881476  0.810192   
b       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
d -0.470109 -0.858757  1.081208 -0.546980  0.238313  0.213670  0.166443   

         s7        s8        s9  
a  0.772715  0.876834  0.519280  
c -0.826157 -0.697199  0.141897  
b       NaN       NaN       NaN  
d -1.235757  0.894851 -2.143308

In [55]:
r1.sort_index(axis=1)

s0        s1        s2        s3        s4        s5        s6  \
a  0.106428 -0.613459 -1.350452  1.239993 -0.872730 -1.365315 -1.747859   
c  0.087469  0.296845 -1.006550  0.179500 -0.677944  1.881476  0.810192   
b       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
d -0.470109 -0.858757  1.081208 -0.546980  0.238313  0.213670  0.166443   

         s7        s8        s9  
a  0.772715  0.876834  0.519280  
c -0.826157 -0.697199  0.141897  
b       NaN       NaN       NaN  
d -1.235757  0.894851 -2.143308

In [58]:
#groupb
animal_df=pd.DataFrame({'name':['dog','cat','cow','dog','cat'],
                        'place':['zoo','ooo','zoo','oo','oo'],
                        'feature':['s','m','c','c','u']})

In [60]:
animal_df

name place feature
0  dog   zoo       s
1  cat   ooo       m
2  cow   zoo       c
3  dog    oo       c
4  cat    oo       u

In [62]:
animal_df.groupby('name').count()

place  feature
name                
cat       2        2
cow       1        1
dog       2        2

In [71]:
animal_df.groupby('name').sum()

place feature
name               
cat   ooooo      mu
cow     zoo       c
dog   zoooo      sc

In [83]:
animal_df=pd.DataFrame({'name':['dog','cat','cow','dog','cat'],
                        'place':['zoo','ooo','zoo','oo','oo'],
                        'no_legs':['4','2','3','4','np.nan']})

In [84]:
animal_df

name place no_legs
0  dog   zoo       4
1  cat   ooo       2
2  cow   zoo       3
3  dog    oo       4
4  cat    oo  np.nan

In [88]:
animal_df['rank']=animal_df('no-legs').rank()

TypeError: 'DataFrame' object is not callable

In [75]:
animal_df

name place feature
0  dog   zoo       s
1  cat   ooo       m
2  cow   zoo       c
3  dog    oo       c
4  cat    oo       u

In [ ]:
animal_df['max-rank']

In [89]:
ani_df("pct-rank")=ani_df('no-legs').rank(pct=true)
ani_df

SyntaxError: can't assign to function call (<ipython-input-89-161fd12da5b3>, line 1)

In [93]:
#categories
data_Frame=pd.DataFrame({'x':[1,2,3,4,5],'y':[6,7,8,9,10]})
data_Frame

x   y
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10

In [94]:
data_Frame["cc"]=data_Frame['y'].astype('category')

In [95]:
data_Frame

x   y  cc
0  1   6   6
1  2   7   7
2  3   8   8
3  4   9   9
4  5  10  10

In [96]:
data_Frame['cc']

0     6
1     7
2     8
3     9
4    10
Name: cc, dtype: category
Categories (5, int64): [6, 7, 8, 9, 10]

In [97]:
data_Frame["cc"].cat.categories=["good","dad","wrost","very bad","very good"]
data_Frame

x   y         cc
0  1   6       good
1  2   7        dad
2  3   8      wrost
3  4   9   very bad
4  5  10  very good

In [98]:
data_Frame["cc"]=data_Frame["cc"].set_categories=["good","dad","wrost","very bad","very good"]
data_Frame

x   y         cc
0  1   6       good
1  2   7        dad
2  3   8      wrost
3  4   9   very bad
4  5  10  very good

In [99]:
data_Frame.sort_values("cc")

x   y         cc
1  2   7        dad
0  1   6       good
3  4   9   very bad
4  5  10  very good
2  3   8      wrost

In [101]:
data_Frame.groupby("cc").sum()

x   y
cc              
dad        2   7
good       1   6
very bad   4   9
very good  5  10
wrost      3   8

In [3]:
import pandas as pd

In [6]:
# reading the data
df=pd.read_table("ex1.csv")

C:\Users\public\anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  
